# Generated by Django 3.1 on 2022-02-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=30)),
                ('productnickname', models.CharField(max_length=30, null=True)),
                ('productimageurl', models.URLField(null=True)),
                ('productqty', models.IntegerField(default=0)),
                ('insdttm', models.DateTimeField(auto_now_add=True)),
                ('upddttm', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteorvendor.vendor')),
            ],
        ),
    ]
