# Generated by Django 3.1 on 2022-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteorvendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=30)),
                ('ownerid', models.CharField(max_length=30)),
                ('oweneremail', models.EmailField(max_length=128, null=True)),
                ('owneraccount', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productaccount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendoraccount',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
