# Generated by Django 3.1 on 2022-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteorvendor', '0003_auto_20220324_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ownerchainaccount',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ownerproduct',
            name='ownerproductchainaccount',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorchainaccount',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
