# Generated by Django 3.1 on 2022-04-01 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meteorvendor', '0004_auto_20220324_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerproduct',
            name='insdttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerproduct',
            name='upddttm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
