# Generated by Django 3.1 on 2022-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteorvendor', '0007_auto_20220410_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='vendorYN',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ownerproduct',
            name='issuedyn',
            field=models.BooleanField(default=False),
        ),
    ]
